site_name: Vernesity V2 Documentation
theme:
  name: material
  features:
    - navigation.tracking
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: deep purple
      accent: blue
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: blue

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Emvith
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


